import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const en = {
  savePage: 'Save this page', saved: 'Saved', manager: 'Open manager', search: 'Search bookmarks', chooseList: 'Choose a list', tags: 'Tags', save: 'Save', cancel: 'Cancel', bookmarks: 'Bookmarks', lists: 'Lists', all: 'All', newList: 'New list', rename: 'Rename', delete: 'Delete', edit: 'Edit', moveUp: 'Move up', moveDown: 'Move down', noBookmarks: 'No bookmarks found', sortNewest: 'Newest', sortOldest: 'Oldest', sortAZ: 'A–Z', import: 'Import', export: 'Export', settings: 'Settings', account: 'Account', signIn: 'Sign in to Nori', signOut: 'Sign out', sync: 'Sync now', localOnly: 'Local only', freePlan: 'Free plan — cloud sync unavailable', synced: 'Synced', syncing: 'Syncing…', theme: 'Theme', language: 'Language', system: 'System', light: 'Light', dark: 'Dark', title: 'Title', url: 'URL', list: 'List', visible: 'Visible', history: 'Recently opened', changelog: 'Changelog', managePlan: 'Manage plan', about: 'About Nori', invalidFile: 'This file could not be imported.', confirmDeleteList: 'Delete this list and its bookmarks?', quickHint: 'Save and find pages without leaving your tab.', updated: 'Updated', copy: 'Copy URL', open: 'Open', filterTags: 'Filter by tags', showFavicons: 'Show favicons', searchProvider: 'Search provider', google: 'Google', duckduckgo: 'DuckDuckGo', backup: 'Nori JSON backup', html: 'Browser HTML', text: 'Plain text', close: 'Close', error: 'Something went wrong', noAccount: 'Not signed in', plan: 'Plan', lastSync: 'Last synced', never: 'Never', offlineEdits: 'Edits stay on this device and will sync when eligible.', addBookmark: 'Add bookmark', recent: 'Recent', currentPage: 'Current page', duplicate: 'Already saved in this list', required: 'Required field', confirm: 'Confirm', localProfile: 'Local profile', version: 'Version 0.1.0', privacy: 'No page content is read. Nori only receives links you choose to save.'
}

const partials: Record<string, Partial<typeof en>> = {
  ar: { savePage: 'حفظ هذه الصفحة', manager: 'فتح المدير', search: 'بحث في الإشارات', save: 'حفظ', cancel: 'إلغاء', bookmarks: 'الإشارات المرجعية', lists: 'القوائم', settings: 'الإعدادات', signIn: 'تسجيل الدخول إلى Nori', signOut: 'تسجيل الخروج', sync: 'مزامنة الآن', delete: 'حذف', edit: 'تعديل' },
  el: { savePage: 'Αποθήκευση σελίδας', manager: 'Άνοιγμα διαχείρισης', search: 'Αναζήτηση σελιδοδεικτών', save: 'Αποθήκευση', cancel: 'Ακύρωση', bookmarks: 'Σελιδοδείκτες', lists: 'Λίστες', settings: 'Ρυθμίσεις', signIn: 'Σύνδεση στο Nori', signOut: 'Αποσύνδεση', sync: 'Συγχρονισμός τώρα' },
  es: { savePage: 'Guardar esta página', manager: 'Abrir gestor', search: 'Buscar marcadores', save: 'Guardar', cancel: 'Cancelar', bookmarks: 'Marcadores', lists: 'Listas', settings: 'Ajustes', signIn: 'Iniciar sesión en Nori', signOut: 'Cerrar sesión', sync: 'Sincronizar ahora', delete: 'Eliminar', edit: 'Editar' },
  fr: { savePage: 'Enregistrer cette page', manager: 'Ouvrir le gestionnaire', search: 'Rechercher des favoris', save: 'Enregistrer', cancel: 'Annuler', bookmarks: 'Favoris', lists: 'Listes', settings: 'Réglages', signIn: 'Se connecter à Nori', signOut: 'Se déconnecter', sync: 'Synchroniser', delete: 'Supprimer', edit: 'Modifier' },
  it: { savePage: 'Salva questa pagina', manager: 'Apri gestore', search: 'Cerca segnalibri', save: 'Salva', cancel: 'Annulla', bookmarks: 'Segnalibri', lists: 'Elenchi', settings: 'Impostazioni', signIn: 'Accedi a Nori', signOut: 'Esci', sync: 'Sincronizza ora', delete: 'Elimina', edit: 'Modifica' },
  pl: { savePage: 'Zapisz tę stronę', manager: 'Otwórz menedżera', search: 'Szukaj zakładek', save: 'Zapisz', cancel: 'Anuluj', bookmarks: 'Zakładki', lists: 'Listy', settings: 'Ustawienia', signIn: 'Zaloguj się do Nori', signOut: 'Wyloguj', sync: 'Synchronizuj', delete: 'Usuń', edit: 'Edytuj' },
  pt_BR: { savePage: 'Salvar esta página', manager: 'Abrir gerenciador', search: 'Pesquisar favoritos', save: 'Salvar', cancel: 'Cancelar', bookmarks: 'Favoritos', lists: 'Listas', settings: 'Configurações', signIn: 'Entrar no Nori', signOut: 'Sair', sync: 'Sincronizar agora', delete: 'Excluir', edit: 'Editar' },
  sv: { savePage: 'Spara den här sidan', manager: 'Öppna hanteraren', search: 'Sök bokmärken', save: 'Spara', cancel: 'Avbryt', bookmarks: 'Bokmärken', lists: 'Listor', settings: 'Inställningar', signIn: 'Logga in på Nori', signOut: 'Logga ut', sync: 'Synkronisera nu', delete: 'Ta bort', edit: 'Redigera' },
  tr: { savePage: 'Bu sayfayı kaydet', manager: 'Yöneticiyi aç', search: 'Yer imlerinde ara', save: 'Kaydet', cancel: 'İptal', bookmarks: 'Yer imleri', lists: 'Listeler', settings: 'Ayarlar', signIn: "Nori'ye giriş yap", signOut: 'Çıkış yap', sync: 'Şimdi eşitle', delete: 'Sil', edit: 'Düzenle' },
  zh_Hans: { savePage: '保存此页面', manager: '打开管理器', search: '搜索书签', save: '保存', cancel: '取消', bookmarks: '书签', lists: '列表', settings: '设置', signIn: '登录 Nori', signOut: '退出登录', sync: '立即同步', delete: '删除', edit: '编辑', newList: '新建列表', noBookmarks: '未找到书签' },
  zh_Hant: { savePage: '儲存此頁面', manager: '開啟管理器', search: '搜尋書籤', save: '儲存', cancel: '取消', bookmarks: '書籤', lists: '清單', settings: '設定', signIn: '登入 Nori', signOut: '登出', sync: '立即同步', delete: '刪除', edit: '編輯', newList: '新增清單', noBookmarks: '找不到書籤' },
}

const resources = Object.fromEntries(['en', ...Object.keys(partials)].map((language) => [language, { translation: { ...en, ...(partials[language] || {}) } }]))

void i18n.use(initReactI18next).init({ resources, lng: 'en', fallbackLng: 'en', interpolation: { escapeValue: false } })

export default i18n
export const languages = ['ar', 'el', 'en', 'es', 'fr', 'it', 'pl', 'pt_BR', 'sv', 'tr', 'zh_Hans', 'zh_Hant']
