default_platform(:ios)

platform :ios do
  desc "Upload screenshots to App Store Connect"
  lane :upload_screenshots do
    upload_to_app_store(
      skip_binary_upload: true,
      skip_metadata: true,
      skip_screenshots: false
    )
  end
end
