#!/usr/bin/env bun
/**
 * Regenerates lib/tokens.css from lib/design-tokens.js.
 *
 * The CSS is checked in so no build step has to run before Tailwind does; this
 * script exists so the channel values only ever live in one place. Run it after
 * editing lib/design-tokens.js:
 *
 *   bun run tokens
 */

import { writeFileSync } from 'fs'
import { join } from 'path'
import { ACCENT_RAMPS, DANGER_RAMP, DEFAULT_ACCENT, RAMP_STEPS, STRUCTURAL } from '../lib/design-tokens'

const HEADER = `/* GENERATED by scripts/build-tokens.ts - run "bun run tokens" after editing
   lib/design-tokens.js. Shared by the app, the browser extension and the
   desktop shell.

   These live ahead of the @tailwind directives on purpose: inside @layer base
   Tailwind folds :root into its own reset and drops .dark:root entirely.

   Structural tokens flip with the color scheme, so a component writes
   bg-surface once instead of "bg-white dark:bg-stone-900". The accent and
   danger ramps do not flip - components pick the step they want with a dark:
   variant - which is what lets an accent swap be one flat set of overrides.
   The exception is --nori-accent-fill / --nori-accent-fill-pressed, which
   lib/accent.ts resolves per scheme so a near-black accent can come back as
   near-white on the dark canvas. */`

const light: string[] = []
const dark: string[] = []
for (const [name, [lightChannels, darkChannels]] of Object.entries(STRUCTURAL)) {
  light.push(`  --nori-${name}: ${lightChannels};`)
  if (darkChannels !== lightChannels) dark.push(`  --nori-${name}: ${darkChannels};`)
}

const ramp = (prefix: string, channels: readonly string[]) =>
  RAMP_STEPS.map((step, index) => `  --nori-${prefix}-${step}: ${channels[index]};`).join('\n')

const css = `${HEADER}

:root {
${light.join('\n')}

  /* Default accent: ${DEFAULT_ACCENT}. Replaced at runtime by the user's choice. */
${ramp('accent', ACCENT_RAMPS[DEFAULT_ACCENT])}
  --nori-accent-on: 255 255 255;
  --nori-accent-fill: ${ACCENT_RAMPS[DEFAULT_ACCENT][RAMP_STEPS.indexOf(600)]};
  --nori-accent-fill-pressed: ${ACCENT_RAMPS[DEFAULT_ACCENT][RAMP_STEPS.indexOf(700)]};

${ramp('danger', DANGER_RAMP)}
}

.dark:root {
${dark.join('\n')}
}
`

const target = join(import.meta.dir, '..', 'lib', 'tokens.css')
writeFileSync(target, css)
console.log(`wrote ${target}`)
