package main

import (
	"context"
	_ "embed"
	"log"
	"os"
	"strings"
	"time"

	"github.com/wailsapp/wails/v3/pkg/application"
	"github.com/wailsapp/wails/v3/pkg/updater"
	"github.com/wailsapp/wails/v3/pkg/updater/providers/endpoint"
)

//go:embed version.txt
var versionFile string

// updateKey is the Ed25519 public key that signs the update manifest's
// artifact digests, pinned at build time so the manifest cannot nominate its
// own trust anchor. Generated by scripts/gen-signing-key.sh; the private half
// lives in the DESKTOP_UPDATE_SIGNING_KEY repository secret.
//
//go:embed update-key.pem
var updateKey []byte

// Version is the running desktop version. version.txt is the single source of
// truth: the release workflow reads it too, and refuses to publish when the
// pushed tag disagrees with it.
var Version = strings.TrimSpace(versionFile)

// manifestURL points at a rolling `desktop-latest` release whose only asset is
// the update manifest. The versioned `desktop/v*` tags cannot serve it: the
// repo's releases/latest pointer belongs to the mobile app, and the GitHub
// updater provider can't read a `desktop/v*` tag as a semver anyway.
const manifestURL = "https://github.com/nonbili/Nori/releases/download/desktop-latest/latest.json"

// checkInterval polls on a timer for sessions long enough to outlive the
// startup check below.
const checkInterval = 24 * time.Hour

// initUpdater wires up the Wails updater, which swaps the running binary (or
// the .app bundle) in place and offers a restart. The DMG and the NSIS
// installer are first-install channels only; updates arrive as the plain
// archives the manifest points at.
func initUpdater(app *application.App) {
	// Inside an AppImage the running binary lives on a read-only mount, and
	// the path an in-place swap would target is the mount, not the image the
	// user actually launched. Those builds update through the AppImage.
	if os.Getenv("APPIMAGE") != "" {
		return
	}

	provider, err := endpoint.New(endpoint.Config{URL: manifestURL, Channel: "stable"})
	if err != nil {
		log.Printf("updater: %v", err)
		return
	}
	if err := app.Updater.Init(updater.Config{
		CurrentVersion: Version,
		Providers:      []updater.Provider{provider},
		PublicKey:      updateKey,
		CheckInterval:  checkInterval,
	}); err != nil {
		log.Printf("updater: %v", err)
		return
	}

	// The timer's first tick is a whole interval away, so short sessions would
	// never check. Check silently on startup and only hand over to
	// CheckAndInstall — which owns the update window — when there is something
	// to show; CheckAndInstall alone would pop a "you're up to date" window on
	// every launch.
	go func() {
		ctx := context.Background()
		rel, err := app.Updater.Check(ctx)
		if err != nil || rel == nil {
			return
		}
		if err := app.Updater.CheckAndInstall(ctx); err != nil {
			log.Printf("updater: %v", err)
		}
	}()
}
